name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build helper
    - name: Build ptylib
      run: |
        cd helper
        cc -shared pty.c -shared -o libpty.dylib
        
    # Restore packages
    - name: Restore
      run: msbuild /t:restore

    # Build
    - name: Build
      run: msbuild /t:build

    # Test
    - name: Test
      run: dotnet test Tests/Tests.csproj
